// This is the unpowered netlist.
/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module CPU_top(clk, reset, control, result);
  input clk;
  wire clk;
  input control;
  wire control;
  input reset;
  wire reset;
  output [31:0] result;
  wire [31:0] result;
  sky130_fd_sc_hd__conb_1 _00_ (
    .LO(result[0])
  );
  sky130_fd_sc_hd__conb_1 _01_ (
    .LO(result[1])
  );
  sky130_fd_sc_hd__conb_1 _02_ (
    .LO(result[2])
  );
  sky130_fd_sc_hd__conb_1 _03_ (
    .LO(result[3])
  );
  sky130_fd_sc_hd__conb_1 _04_ (
    .LO(result[4])
  );
  sky130_fd_sc_hd__conb_1 _05_ (
    .LO(result[5])
  );
  sky130_fd_sc_hd__conb_1 _06_ (
    .LO(result[6])
  );
  sky130_fd_sc_hd__conb_1 _07_ (
    .LO(result[7])
  );
  sky130_fd_sc_hd__conb_1 _08_ (
    .LO(result[8])
  );
  sky130_fd_sc_hd__conb_1 _09_ (
    .LO(result[9])
  );
  sky130_fd_sc_hd__conb_1 _10_ (
    .LO(result[10])
  );
  sky130_fd_sc_hd__conb_1 _11_ (
    .LO(result[11])
  );
  sky130_fd_sc_hd__conb_1 _12_ (
    .LO(result[12])
  );
  sky130_fd_sc_hd__conb_1 _13_ (
    .LO(result[13])
  );
  sky130_fd_sc_hd__conb_1 _14_ (
    .LO(result[14])
  );
  sky130_fd_sc_hd__conb_1 _15_ (
    .LO(result[15])
  );
  sky130_fd_sc_hd__conb_1 _16_ (
    .LO(result[16])
  );
  sky130_fd_sc_hd__conb_1 _17_ (
    .LO(result[17])
  );
  sky130_fd_sc_hd__conb_1 _18_ (
    .LO(result[18])
  );
  sky130_fd_sc_hd__conb_1 _19_ (
    .LO(result[19])
  );
  sky130_fd_sc_hd__conb_1 _20_ (
    .LO(result[20])
  );
  sky130_fd_sc_hd__conb_1 _21_ (
    .LO(result[21])
  );
  sky130_fd_sc_hd__conb_1 _22_ (
    .LO(result[22])
  );
  sky130_fd_sc_hd__conb_1 _23_ (
    .LO(result[23])
  );
  sky130_fd_sc_hd__conb_1 _24_ (
    .LO(result[24])
  );
  sky130_fd_sc_hd__conb_1 _25_ (
    .LO(result[25])
  );
  sky130_fd_sc_hd__conb_1 _26_ (
    .LO(result[26])
  );
  sky130_fd_sc_hd__conb_1 _27_ (
    .LO(result[27])
  );
  sky130_fd_sc_hd__conb_1 _28_ (
    .LO(result[28])
  );
  sky130_fd_sc_hd__conb_1 _29_ (
    .LO(result[29])
  );
  sky130_fd_sc_hd__conb_1 _30_ (
    .LO(result[30])
  );
  sky130_fd_sc_hd__conb_1 _31_ (
    .LO(result[31])
  );
endmodule

