// This is the unpowered netlist.
/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module top(clk, rst, seg);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  input clk;
  wire clk;
  wire \counter_inst.count[0] ;
  wire \counter_inst.count[1] ;
  wire \counter_inst.count[2] ;
  wire \counter_inst.count[3] ;
  input rst;
  wire rst;
  output [6:0] seg;
  wire [6:0] seg;
  sky130_fd_sc_hd__or4b_2 _21_ (
    .A(\counter_inst.count[0] ),
    .B(\counter_inst.count[1] ),
    .C(\counter_inst.count[3] ),
    .D_N(\counter_inst.count[2] ),
    .X(_08_)
  );
  sky130_fd_sc_hd__and2b_2 _22_ (
    .A_N(\counter_inst.count[0] ),
    .B(_08_),
    .X(_09_)
  );
  sky130_fd_sc_hd__buf_1 _23_ (
    .A(_09_),
    .X(_00_)
  );
  sky130_fd_sc_hd__and2b_2 _24_ (
    .A_N(\counter_inst.count[0] ),
    .B(\counter_inst.count[1] ),
    .X(_10_)
  );
  sky130_fd_sc_hd__and2b_2 _25_ (
    .A_N(\counter_inst.count[1] ),
    .B(\counter_inst.count[0] ),
    .X(_11_)
  );
  sky130_fd_sc_hd__or2_2 _26_ (
    .A(_10_),
    .B(_11_),
    .X(_12_)
  );
  sky130_fd_sc_hd__buf_1 _27_ (
    .A(_12_),
    .X(_01_)
  );
  sky130_fd_sc_hd__nand3_2 _28_ (
    .A(\counter_inst.count[0] ),
    .B(\counter_inst.count[1] ),
    .C(\counter_inst.count[2] ),
    .Y(_13_)
  );
  sky130_fd_sc_hd__a21o_2 _29_ (
    .A1(\counter_inst.count[0] ),
    .A2(\counter_inst.count[1] ),
    .B1(\counter_inst.count[2] ),
    .X(_14_)
  );
  sky130_fd_sc_hd__and3_2 _30_ (
    .A(_08_),
    .B(_13_),
    .C(_14_),
    .X(_15_)
  );
  sky130_fd_sc_hd__buf_1 _31_ (
    .A(_15_),
    .X(_02_)
  );
  sky130_fd_sc_hd__xnor2_2 _32_ (
    .A(\counter_inst.count[3] ),
    .B(_13_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__or3_2 _33_ (
    .A(\counter_inst.count[0] ),
    .B(\counter_inst.count[1] ),
    .C(\counter_inst.count[3] ),
    .X(_16_)
  );
  sky130_fd_sc_hd__buf_1 _34_ (
    .A(_16_),
    .X(seg[5])
  );
  sky130_fd_sc_hd__or2_2 _35_ (
    .A(\counter_inst.count[3] ),
    .B(\counter_inst.count[2] ),
    .X(_17_)
  );
  sky130_fd_sc_hd__and2_2 _36_ (
    .A(seg[5]),
    .B(_17_),
    .X(_18_)
  );
  sky130_fd_sc_hd__buf_1 _37_ (
    .A(_18_),
    .X(seg[1])
  );
  sky130_fd_sc_hd__or2_2 _38_ (
    .A(_11_),
    .B(_17_),
    .X(_19_)
  );
  sky130_fd_sc_hd__buf_1 _39_ (
    .A(_19_),
    .X(seg[3])
  );
  sky130_fd_sc_hd__o21a_2 _40_ (
    .A1(_10_),
    .A2(_17_),
    .B1(_08_),
    .X(seg[2])
  );
  sky130_fd_sc_hd__or2_2 _41_ (
    .A(\counter_inst.count[0] ),
    .B(_17_),
    .X(_20_)
  );
  sky130_fd_sc_hd__buf_1 _42_ (
    .A(_20_),
    .X(seg[4])
  );
  sky130_fd_sc_hd__a2bb2o_2 _43_ (
    .A1_N(\counter_inst.count[1] ),
    .A2_N(\counter_inst.count[2] ),
    .B1(seg[5]),
    .B2(_17_),
    .X(seg[6])
  );
  sky130_fd_sc_hd__inv_2 _44_ (
    .A(rst),
    .Y(_04_)
  );
  sky130_fd_sc_hd__inv_2 _45_ (
    .A(rst),
    .Y(_05_)
  );
  sky130_fd_sc_hd__inv_2 _46_ (
    .A(rst),
    .Y(_06_)
  );
  sky130_fd_sc_hd__inv_2 _47_ (
    .A(rst),
    .Y(_07_)
  );
  sky130_fd_sc_hd__dfrtp_2 _48_ (
    .CLK(clk),
    .D(_00_),
    .Q(\counter_inst.count[0] ),
    .RESET_B(_04_)
  );
  sky130_fd_sc_hd__dfrtp_2 _49_ (
    .CLK(clk),
    .D(_01_),
    .Q(\counter_inst.count[1] ),
    .RESET_B(_05_)
  );
  sky130_fd_sc_hd__dfrtp_2 _50_ (
    .CLK(clk),
    .D(_02_),
    .Q(\counter_inst.count[2] ),
    .RESET_B(_06_)
  );
  sky130_fd_sc_hd__dfrtp_2 _51_ (
    .CLK(clk),
    .D(_03_),
    .Q(\counter_inst.count[3] ),
    .RESET_B(_07_)
  );
  sky130_fd_sc_hd__buf_2 _52_ (
    .A(seg[3]),
    .X(seg[0])
  );
endmodule

