/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module TopModule(clk, rst, control, Result, an, seg);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  output [31:0] Result;
  wire [31:0] Result;
  output [3:0] an;
  wire [3:0] an;
  input clk;
  wire clk;
  input control;
  wire control;
  wire \display.digit_select[0] ;
  wire \display.digit_select[1] ;
  wire \display.digit_select[2] ;
  wire \display.refresh_counter[0] ;
  wire \display.refresh_counter[10] ;
  wire \display.refresh_counter[11] ;
  wire \display.refresh_counter[12] ;
  wire \display.refresh_counter[13] ;
  wire \display.refresh_counter[14] ;
  wire \display.refresh_counter[15] ;
  wire \display.refresh_counter[16] ;
  wire \display.refresh_counter[1] ;
  wire \display.refresh_counter[2] ;
  wire \display.refresh_counter[3] ;
  wire \display.refresh_counter[4] ;
  wire \display.refresh_counter[5] ;
  wire \display.refresh_counter[6] ;
  wire \display.refresh_counter[7] ;
  wire \display.refresh_counter[8] ;
  wire \display.refresh_counter[9] ;
  input rst;
  wire rst;
  output [6:0] seg;
  wire [6:0] seg;
  sky130_fd_sc_hd__or3_2 _064_ (
    .A(\display.digit_select[0] ),
    .B(\display.digit_select[2] ),
    .C(\display.digit_select[1] ),
    .X(_030_)
  );
  sky130_fd_sc_hd__buf_1 _065_ (
    .A(_030_),
    .X(an[0])
  );
  sky130_fd_sc_hd__inv_2 _066_ (
    .A(\display.digit_select[0] ),
    .Y(_031_)
  );
  sky130_fd_sc_hd__or3_2 _067_ (
    .A(_031_),
    .B(\display.digit_select[2] ),
    .C(\display.digit_select[1] ),
    .X(_032_)
  );
  sky130_fd_sc_hd__buf_1 _068_ (
    .A(_032_),
    .X(an[1])
  );
  sky130_fd_sc_hd__or3b_2 _069_ (
    .A(\display.digit_select[0] ),
    .B(\display.digit_select[2] ),
    .C_N(\display.digit_select[1] ),
    .X(_033_)
  );
  sky130_fd_sc_hd__buf_1 _070_ (
    .A(_033_),
    .X(an[2])
  );
  sky130_fd_sc_hd__nand2_2 _071_ (
    .A(\display.digit_select[0] ),
    .B(\display.digit_select[1] ),
    .Y(_034_)
  );
  sky130_fd_sc_hd__or2_2 _072_ (
    .A(\display.digit_select[2] ),
    .B(_034_),
    .X(_035_)
  );
  sky130_fd_sc_hd__buf_1 _073_ (
    .A(_035_),
    .X(an[3])
  );
  sky130_fd_sc_hd__inv_2 _074_ (
    .A(\display.refresh_counter[0] ),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2_2 _075_ (
    .A(\display.refresh_counter[1] ),
    .B(\display.refresh_counter[0] ),
    .Y(_036_)
  );
  sky130_fd_sc_hd__or2_2 _076_ (
    .A(\display.refresh_counter[1] ),
    .B(\display.refresh_counter[0] ),
    .X(_037_)
  );
  sky130_fd_sc_hd__and2_2 _077_ (
    .A(_036_),
    .B(_037_),
    .X(_038_)
  );
  sky130_fd_sc_hd__buf_1 _078_ (
    .A(_038_),
    .X(_008_)
  );
  sky130_fd_sc_hd__xnor2_2 _079_ (
    .A(\display.refresh_counter[2] ),
    .B(_036_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__and4_2 _080_ (
    .A(\display.refresh_counter[1] ),
    .B(\display.refresh_counter[0] ),
    .C(\display.refresh_counter[3] ),
    .D(\display.refresh_counter[2] ),
    .X(_039_)
  );
  sky130_fd_sc_hd__buf_1 _081_ (
    .A(_039_),
    .X(_040_)
  );
  sky130_fd_sc_hd__a31o_2 _082_ (
    .A1(\display.refresh_counter[1] ),
    .A2(\display.refresh_counter[0] ),
    .A3(\display.refresh_counter[2] ),
    .B1(\display.refresh_counter[3] ),
    .X(_041_)
  );
  sky130_fd_sc_hd__and2b_2 _083_ (
    .A_N(_040_),
    .B(_041_),
    .X(_042_)
  );
  sky130_fd_sc_hd__buf_1 _084_ (
    .A(_042_),
    .X(_010_)
  );
  sky130_fd_sc_hd__xor2_2 _085_ (
    .A(\display.refresh_counter[4] ),
    .B(_040_),
    .X(_011_)
  );
  sky130_fd_sc_hd__nand2_2 _086_ (
    .A(\display.refresh_counter[4] ),
    .B(_040_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xnor2_2 _087_ (
    .A(\display.refresh_counter[5] ),
    .B(_043_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__and4_2 _088_ (
    .A(\display.refresh_counter[5] ),
    .B(\display.refresh_counter[4] ),
    .C(\display.refresh_counter[6] ),
    .D(_040_),
    .X(_044_)
  );
  sky130_fd_sc_hd__a31o_2 _089_ (
    .A1(\display.refresh_counter[5] ),
    .A2(\display.refresh_counter[4] ),
    .A3(_040_),
    .B1(\display.refresh_counter[6] ),
    .X(_045_)
  );
  sky130_fd_sc_hd__and2b_2 _090_ (
    .A_N(_044_),
    .B(_045_),
    .X(_046_)
  );
  sky130_fd_sc_hd__buf_1 _091_ (
    .A(_046_),
    .X(_013_)
  );
  sky130_fd_sc_hd__nor2_2 _092_ (
    .A(\display.refresh_counter[7] ),
    .B(_044_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__and4_2 _093_ (
    .A(\display.refresh_counter[5] ),
    .B(\display.refresh_counter[4] ),
    .C(\display.refresh_counter[7] ),
    .D(\display.refresh_counter[6] ),
    .X(_048_)
  );
  sky130_fd_sc_hd__and2_2 _094_ (
    .A(_040_),
    .B(_048_),
    .X(_049_)
  );
  sky130_fd_sc_hd__nor2_2 _095_ (
    .A(_047_),
    .B(_049_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xor2_2 _096_ (
    .A(\display.refresh_counter[8] ),
    .B(_049_),
    .X(_015_)
  );
  sky130_fd_sc_hd__and3_2 _097_ (
    .A(\display.refresh_counter[9] ),
    .B(\display.refresh_counter[8] ),
    .C(_049_),
    .X(_050_)
  );
  sky130_fd_sc_hd__a31o_2 _098_ (
    .A1(\display.refresh_counter[8] ),
    .A2(_040_),
    .A3(_048_),
    .B1(\display.refresh_counter[9] ),
    .X(_051_)
  );
  sky130_fd_sc_hd__and2b_2 _099_ (
    .A_N(_050_),
    .B(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd__buf_1 _100_ (
    .A(_052_),
    .X(_016_)
  );
  sky130_fd_sc_hd__xor2_2 _101_ (
    .A(\display.refresh_counter[10] ),
    .B(_050_),
    .X(_001_)
  );
  sky130_fd_sc_hd__and4_2 _102_ (
    .A(\display.refresh_counter[9] ),
    .B(\display.refresh_counter[8] ),
    .C(\display.refresh_counter[10] ),
    .D(_049_),
    .X(_053_)
  );
  sky130_fd_sc_hd__xor2_2 _103_ (
    .A(\display.refresh_counter[11] ),
    .B(_053_),
    .X(_002_)
  );
  sky130_fd_sc_hd__and4_2 _104_ (
    .A(\display.refresh_counter[9] ),
    .B(\display.refresh_counter[8] ),
    .C(\display.refresh_counter[11] ),
    .D(\display.refresh_counter[10] ),
    .X(_054_)
  );
  sky130_fd_sc_hd__and3_2 _105_ (
    .A(_040_),
    .B(_048_),
    .C(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hd__and2_2 _106_ (
    .A(\display.refresh_counter[12] ),
    .B(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__nor2_2 _107_ (
    .A(\display.refresh_counter[12] ),
    .B(_055_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor2_2 _108_ (
    .A(_056_),
    .B(_057_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand3_2 _109_ (
    .A(\display.refresh_counter[13] ),
    .B(\display.refresh_counter[12] ),
    .C(_055_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__o21a_2 _110_ (
    .A1(\display.refresh_counter[13] ),
    .A2(_056_),
    .B1(_058_),
    .X(_004_)
  );
  sky130_fd_sc_hd__xnor2_2 _111_ (
    .A(\display.refresh_counter[14] ),
    .B(_058_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__and2_2 _112_ (
    .A(\display.refresh_counter[15] ),
    .B(\display.refresh_counter[14] ),
    .X(_059_)
  );
  sky130_fd_sc_hd__and4_2 _113_ (
    .A(\display.refresh_counter[13] ),
    .B(\display.refresh_counter[12] ),
    .C(_055_),
    .D(_059_),
    .X(_060_)
  );
  sky130_fd_sc_hd__a41o_2 _114_ (
    .A1(\display.refresh_counter[13] ),
    .A2(\display.refresh_counter[12] ),
    .A3(\display.refresh_counter[14] ),
    .A4(_055_),
    .B1(\display.refresh_counter[15] ),
    .X(_061_)
  );
  sky130_fd_sc_hd__and2b_2 _115_ (
    .A_N(_060_),
    .B(_061_),
    .X(_062_)
  );
  sky130_fd_sc_hd__buf_1 _116_ (
    .A(_062_),
    .X(_006_)
  );
  sky130_fd_sc_hd__xor2_2 _117_ (
    .A(\display.refresh_counter[16] ),
    .B(_060_),
    .X(_007_)
  );
  sky130_fd_sc_hd__or4_2 _118_ (
    .A(\display.refresh_counter[3] ),
    .B(\display.refresh_counter[2] ),
    .C(\display.refresh_counter[5] ),
    .D(\display.refresh_counter[4] ),
    .X(_063_)
  );
  sky130_fd_sc_hd__or2_2 _119_ (
    .A(_037_),
    .B(_063_),
    .X(_020_)
  );
  sky130_fd_sc_hd__or3_2 _120_ (
    .A(\display.refresh_counter[15] ),
    .B(\display.refresh_counter[14] ),
    .C(\display.refresh_counter[16] ),
    .X(_021_)
  );
  sky130_fd_sc_hd__or4_2 _121_ (
    .A(\display.refresh_counter[11] ),
    .B(\display.refresh_counter[10] ),
    .C(\display.refresh_counter[13] ),
    .D(\display.refresh_counter[12] ),
    .X(_022_)
  );
  sky130_fd_sc_hd__or4_2 _122_ (
    .A(\display.refresh_counter[7] ),
    .B(\display.refresh_counter[6] ),
    .C(\display.refresh_counter[9] ),
    .D(\display.refresh_counter[8] ),
    .X(_023_)
  );
  sky130_fd_sc_hd__or3_2 _123_ (
    .A(_021_),
    .B(_022_),
    .C(_023_),
    .X(_024_)
  );
  sky130_fd_sc_hd__or3_2 _124_ (
    .A(_031_),
    .B(_020_),
    .C(_024_),
    .X(_025_)
  );
  sky130_fd_sc_hd__o21ai_2 _125_ (
    .A1(_020_),
    .A2(_024_),
    .B1(_031_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__and2_2 _126_ (
    .A(_025_),
    .B(_026_),
    .X(_027_)
  );
  sky130_fd_sc_hd__buf_1 _127_ (
    .A(_027_),
    .X(_017_)
  );
  sky130_fd_sc_hd__or4_2 _128_ (
    .A(_031_),
    .B(\display.digit_select[1] ),
    .C(_020_),
    .D(_024_),
    .X(_028_)
  );
  sky130_fd_sc_hd__a21bo_2 _129_ (
    .A1(\display.digit_select[1] ),
    .A2(_025_),
    .B1_N(_028_),
    .X(_018_)
  );
  sky130_fd_sc_hd__or3_2 _130_ (
    .A(_034_),
    .B(_020_),
    .C(_024_),
    .X(_029_)
  );
  sky130_fd_sc_hd__xnor2_2 _131_ (
    .A(\display.digit_select[2] ),
    .B(_029_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__dfxtp_2 _132_ (
    .CLK(clk),
    .D(_017_),
    .Q(\display.digit_select[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _133_ (
    .CLK(clk),
    .D(_018_),
    .Q(\display.digit_select[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _134_ (
    .CLK(clk),
    .D(_019_),
    .Q(\display.digit_select[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _135_ (
    .CLK(clk),
    .D(_000_),
    .Q(\display.refresh_counter[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _136_ (
    .CLK(clk),
    .D(_008_),
    .Q(\display.refresh_counter[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _137_ (
    .CLK(clk),
    .D(_009_),
    .Q(\display.refresh_counter[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _138_ (
    .CLK(clk),
    .D(_010_),
    .Q(\display.refresh_counter[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _139_ (
    .CLK(clk),
    .D(_011_),
    .Q(\display.refresh_counter[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _140_ (
    .CLK(clk),
    .D(_012_),
    .Q(\display.refresh_counter[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _141_ (
    .CLK(clk),
    .D(_013_),
    .Q(\display.refresh_counter[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _142_ (
    .CLK(clk),
    .D(_014_),
    .Q(\display.refresh_counter[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _143_ (
    .CLK(clk),
    .D(_015_),
    .Q(\display.refresh_counter[8] )
  );
  sky130_fd_sc_hd__dfxtp_2 _144_ (
    .CLK(clk),
    .D(_016_),
    .Q(\display.refresh_counter[9] )
  );
  sky130_fd_sc_hd__dfxtp_2 _145_ (
    .CLK(clk),
    .D(_001_),
    .Q(\display.refresh_counter[10] )
  );
  sky130_fd_sc_hd__dfxtp_2 _146_ (
    .CLK(clk),
    .D(_002_),
    .Q(\display.refresh_counter[11] )
  );
  sky130_fd_sc_hd__dfxtp_2 _147_ (
    .CLK(clk),
    .D(_003_),
    .Q(\display.refresh_counter[12] )
  );
  sky130_fd_sc_hd__dfxtp_2 _148_ (
    .CLK(clk),
    .D(_004_),
    .Q(\display.refresh_counter[13] )
  );
  sky130_fd_sc_hd__dfxtp_2 _149_ (
    .CLK(clk),
    .D(_005_),
    .Q(\display.refresh_counter[14] )
  );
  sky130_fd_sc_hd__dfxtp_2 _150_ (
    .CLK(clk),
    .D(_006_),
    .Q(\display.refresh_counter[15] )
  );
  sky130_fd_sc_hd__dfxtp_2 _151_ (
    .CLK(clk),
    .D(_007_),
    .Q(\display.refresh_counter[16] )
  );
  sky130_fd_sc_hd__conb_1 _152_ (
    .HI(seg[6])
  );
  sky130_fd_sc_hd__conb_1 _153_ (
    .LO(Result[0])
  );
  sky130_fd_sc_hd__conb_1 _154_ (
    .LO(Result[1])
  );
  sky130_fd_sc_hd__conb_1 _155_ (
    .LO(Result[2])
  );
  sky130_fd_sc_hd__conb_1 _156_ (
    .LO(Result[3])
  );
  sky130_fd_sc_hd__conb_1 _157_ (
    .LO(Result[4])
  );
  sky130_fd_sc_hd__conb_1 _158_ (
    .LO(Result[5])
  );
  sky130_fd_sc_hd__conb_1 _159_ (
    .LO(Result[6])
  );
  sky130_fd_sc_hd__conb_1 _160_ (
    .LO(Result[7])
  );
  sky130_fd_sc_hd__conb_1 _161_ (
    .LO(Result[8])
  );
  sky130_fd_sc_hd__conb_1 _162_ (
    .LO(Result[9])
  );
  sky130_fd_sc_hd__conb_1 _163_ (
    .LO(Result[10])
  );
  sky130_fd_sc_hd__conb_1 _164_ (
    .LO(Result[11])
  );
  sky130_fd_sc_hd__conb_1 _165_ (
    .LO(Result[12])
  );
  sky130_fd_sc_hd__conb_1 _166_ (
    .LO(Result[13])
  );
  sky130_fd_sc_hd__conb_1 _167_ (
    .LO(Result[14])
  );
  sky130_fd_sc_hd__conb_1 _168_ (
    .LO(Result[15])
  );
  sky130_fd_sc_hd__conb_1 _169_ (
    .LO(Result[16])
  );
  sky130_fd_sc_hd__conb_1 _170_ (
    .LO(Result[17])
  );
  sky130_fd_sc_hd__conb_1 _171_ (
    .LO(Result[18])
  );
  sky130_fd_sc_hd__conb_1 _172_ (
    .LO(Result[19])
  );
  sky130_fd_sc_hd__conb_1 _173_ (
    .LO(Result[20])
  );
  sky130_fd_sc_hd__conb_1 _174_ (
    .LO(Result[21])
  );
  sky130_fd_sc_hd__conb_1 _175_ (
    .LO(Result[22])
  );
  sky130_fd_sc_hd__conb_1 _176_ (
    .LO(Result[23])
  );
  sky130_fd_sc_hd__conb_1 _177_ (
    .LO(Result[24])
  );
  sky130_fd_sc_hd__conb_1 _178_ (
    .LO(Result[25])
  );
  sky130_fd_sc_hd__conb_1 _179_ (
    .LO(Result[26])
  );
  sky130_fd_sc_hd__conb_1 _180_ (
    .LO(Result[27])
  );
  sky130_fd_sc_hd__conb_1 _181_ (
    .LO(Result[28])
  );
  sky130_fd_sc_hd__conb_1 _182_ (
    .LO(Result[29])
  );
  sky130_fd_sc_hd__conb_1 _183_ (
    .LO(Result[30])
  );
  sky130_fd_sc_hd__conb_1 _184_ (
    .LO(Result[31])
  );
  sky130_fd_sc_hd__conb_1 _185_ (
    .LO(seg[0])
  );
  sky130_fd_sc_hd__conb_1 _186_ (
    .LO(seg[1])
  );
  sky130_fd_sc_hd__conb_1 _187_ (
    .LO(seg[2])
  );
  sky130_fd_sc_hd__conb_1 _188_ (
    .LO(seg[3])
  );
  sky130_fd_sc_hd__conb_1 _189_ (
    .LO(seg[4])
  );
  sky130_fd_sc_hd__conb_1 _190_ (
    .LO(seg[5])
  );
endmodule
